import type { McpToolServer } from '../toolTypes';
import { registerTool as listDatabases } from './listDatabases';
import { registerTool as getActiveDatabase } from './getActiveDatabase';
import { registerTool as switchDatabase } from './switchDatabase';
import { registerTool as lookupObjectById } from './lookupObjectById';
import { registerTool as searchDatabaseObjects } from './searchDatabaseObjects';
import { registerTool as searchClasses } from './searchClasses';
import { registerTool as getClassDetails } from './getClassDetails';
import { registerTool as getClassDictionary } from './getClassDictionary';
import { registerTool as searchClassDictionary } from './searchClassDictionary';
import { registerTool as getClassAttributes } from './getClassAttributes';
import { registerTool as getAttributeDetails } from './getAttributeDetails';
import { registerTool as getAttributeCreationOptions } from './getAttributeCreationOptions';
import { registerTool as getMethodCreationOptions } from './getMethodCreationOptions';
import { registerTool as getClassProperties } from './getClassProperties';
import { registerTool as getPropertyDetails } from './getPropertyDetails';
import { registerTool as searchMethods } from './searchMethods';
import { registerTool as resolveMethodReference } from './resolveMethodReference';
import { registerTool as getMethodSource } from './getMethodSource';
import { registerTool as updateMethodSource } from './updateMethodSource';
import { registerTool as createClassMethod } from './createClassMethod';
import { registerTool as createClassAttribute } from './createClassAttribute';
import { registerTool as getLifecycleFunctionCatalog } from './getLifecycleFunctionCatalog';
import { registerTool as executeLifecycleMethod } from './executeLifecycleMethod';
import { registerTool as updateDatabase } from './updateDatabase';
import { registerTool as updatePackages } from './updatePackages';
import { registerTool as updateBinaries } from './updateBinaries';
import { registerTool as startClient } from './startClient';
import { registerTool as openClientEntity } from './openClientEntity';
import { registerTool as getSvnFileHistory } from './getSvnFileHistory';
import { registerTool as getPackageSyncChanges } from './getPackageSyncChanges';
import { registerTool as getProductionTasks } from './getProductionTasks';
import { registerTool as getProductionTask } from './getProductionTask';
import { registerTool as getProductionTasksInProgress } from './getProductionTasksInProgress';
import { registerTool as getDfmSource } from './getDfmSource';
import { registerTool as getDfmInheritance } from './getDfmInheritance';
import { registerTool as revealClass } from './revealClass';
import { registerTool as openClass } from './openClass';
import { registerTool as openMethod } from './openMethod';
import { registerTool as revealMethodInClass } from './revealMethodInClass';
import { registerTool as queryReadonly } from './queryReadonly';
import { registerTool as getRecentExtensionErrors } from './getRecentExtensionErrors';
import { registerTool as getExtensionLogs } from './getExtensionLogs';
import { registerTool as getRecentSqlQueries } from './getRecentSqlQueries';
import { registerTool as listClientMcpTools } from './listClientMcpTools';
import { registerTool as callClientMcpTool } from './callClientMcpTool';

/** Register the public MCP tools in a stable order. */
export function registerTools(server: McpToolServer): void {
	listDatabases(server);
	getActiveDatabase(server);
	switchDatabase(server);
	lookupObjectById(server);
	searchDatabaseObjects(server);
	searchClasses(server);
	getClassDetails(server);
	getClassDictionary(server);
	searchClassDictionary(server);
	getClassAttributes(server);
	getAttributeDetails(server);
	getAttributeCreationOptions(server);
	getMethodCreationOptions(server);
	getClassProperties(server);
	getPropertyDetails(server);
	searchMethods(server);
	resolveMethodReference(server);
	getMethodSource(server);
	updateMethodSource(server);
	createClassMethod(server);
	createClassAttribute(server);
	getLifecycleFunctionCatalog(server);
	executeLifecycleMethod(server);
	updateDatabase(server);
	updatePackages(server);
	updateBinaries(server);
	startClient(server);
	openClientEntity(server);
	getSvnFileHistory(server);
	getPackageSyncChanges(server);
	getProductionTasks(server);
	getProductionTask(server);
	getProductionTasksInProgress(server);
	getDfmSource(server);
	getDfmInheritance(server);
	revealClass(server);
	openClass(server);
	openMethod(server);
	revealMethodInClass(server);
	queryReadonly(server);
	getRecentExtensionErrors(server);
	getExtensionLogs(server);
	getRecentSqlQueries(server);
	listClientMcpTools(server);
	callClientMcpTool(server);
}
