import type { McpToolServer } from '../toolTypes';
import { registerTool as listDatabases } from './database/listDatabases';
import { registerTool as getActiveDatabase } from './database/getActiveDatabase';
import { registerTool as switchDatabase } from './database/switchDatabase';
import { registerTool as lookupObjectById } from './database/lookupObjectById';
import { registerTool as checkObjectPackageBinding } from './packages/checkObjectPackageBinding';
import { registerTool as bindObjectsToPackage } from './packages/bindObjectsToPackage';
import { registerTool as searchDatabaseObjects } from './database/searchDatabaseObjects';
import { registerTool as searchClasses } from './classes/searchClasses';
import { registerTool as getClassDetails } from './classes/getClassDetails';
import { registerTool as getClassDictionary } from './classes/getClassDictionary';
import { registerTool as searchClassDictionary } from './classes/searchClassDictionary';
import { registerTool as getClassAttributes } from './classes/getClassAttributes';
import { registerTool as getAttributeDetails } from './classes/getAttributeDetails';
import { registerTool as getAttributeCreationOptions } from './classes/getAttributeCreationOptions';
import { registerTool as getMethodCreationOptions } from './methods/getMethodCreationOptions';
import { registerTool as getClassProperties } from './classes/getClassProperties';
import { registerTool as getPropertyDetails } from './classes/getPropertyDetails';
import { registerTool as searchMethods } from './methods/searchMethods';
import { registerTool as resolveMethodReference } from './methods/resolveMethodReference';
import { registerTool as getMethodSource } from './methods/getMethodSource';
import { registerTool as updateMethodSource } from './methods/updateMethodSource';
import { registerTool as compileMethod } from './methods/compileMethod';
import { registerTool as createClassMethodChecked } from './methods/createClassMethodChecked';
import { registerTool as getMethodCompilationHistory } from './methods/getMethodCompilationHistory';
import { registerTool as getModuleSource } from './sources/getModuleSource';
import { registerTool as updateModuleSource } from './sources/updateModuleSource';
import { registerTool as getLifecycleFunctionCatalog } from './lifecycle/getLifecycleFunctionCatalog';
import { registerTool as executeLifecycleMethod } from './lifecycle/executeLifecycleMethod';
import { registerTool as updateDatabase } from './project/updateDatabase';
import { registerTool as updatePackages } from './project/updatePackages';
import { registerTool as updateBinaries } from './project/updateBinaries';
import { registerTool as startClient } from './client/startClient';
import { registerTool as openClientEntity } from './client/openClientEntity';
import { registerTool as getSvnFileHistory } from './packages/getSvnFileHistory';
import { registerTool as getPackageSyncChanges } from './packages/getPackageSyncChanges';
import { registerTool as getProductionTasks } from './project/getProductionTasks';
import { registerTool as getProductionTask } from './project/getProductionTask';
import { registerTool as getProductionTasksInProgress } from './project/getProductionTasksInProgress';
import { registerTool as getDfmSource } from './sources/getDfmSource';
import { registerTool as getDfmInheritance } from './sources/getDfmInheritance';
import { registerTool as updateDfmSource } from './sources/updateDfmSource';
import { registerTool as revealClass } from './navigation/revealClass';
import { registerTool as openClass } from './navigation/openClass';
import { registerTool as openMethod } from './navigation/openMethod';
import { registerTool as revealMethodInClass } from './navigation/revealMethodInClass';
import { registerTool as queryReadonly } from './database/queryReadonly';
import { registerTool as queryDatabase } from './database/queryDatabase';
import { registerTool as getRecentExtensionErrors } from './diagnostics/getRecentExtensionErrors';
import { registerTool as getExtensionLogs } from './diagnostics/getExtensionLogs';
import { registerTool as getRecentSqlQueries } from './diagnostics/getRecentSqlQueries';
import { registerTool as listClientMcpTools } from './client/listClientMcpTools';
import { registerTool as callClientMcpTool } from './client/callClientMcpTool';
import { registerTool as startClientMcp } from './client/startClientMcp';
import { registerTool as stopClientMcp } from './client/stopClientMcp';
import { registerTool as listNativeClientLogs } from './client/listNativeClientLogs';
import { registerTool as readNativeClientLog } from './client/readNativeClientLog';
import { registerTool as startHttpTestServer } from './http/startHttpTestServer';
import { registerTool as stopHttpTestServer } from './http/stopHttpTestServer';
import { registerTool as getHttpTestServerStatus } from './http/getHttpTestServerStatus';
import { registerTool as callHttpTestServer } from './http/callHttpTestServer';
import { registerTool as listHttpMethods } from './http/listHttpMethods';

/** Register the public MCP tools in a stable order. */
export function registerTools(server: McpToolServer): void {
	listDatabases(server);
	getActiveDatabase(server);
	switchDatabase(server);
	lookupObjectById(server);
	checkObjectPackageBinding(server);
	bindObjectsToPackage(server);
	searchDatabaseObjects(server);
	searchClasses(server);
	getClassDetails(server);
	getClassDictionary(server);
	searchClassDictionary(server);
	getClassAttributes(server);
	getAttributeDetails(server);
	getAttributeCreationOptions(server);
	getMethodCreationOptions(server);
	getClassProperties(server);
	getPropertyDetails(server);
	searchMethods(server);
	resolveMethodReference(server);
	getMethodSource(server);
	updateMethodSource(server);
	createClassMethodChecked(server);
	compileMethod(server);
	getMethodCompilationHistory(server);
	getModuleSource(server);
	updateModuleSource(server);
	getLifecycleFunctionCatalog(server);
	executeLifecycleMethod(server);
	updateDatabase(server);
	updatePackages(server);
	updateBinaries(server);
	startClient(server);
	openClientEntity(server);
	getSvnFileHistory(server);
	getPackageSyncChanges(server);
	getProductionTasks(server);
	getProductionTask(server);
	getProductionTasksInProgress(server);
	getDfmSource(server);
	getDfmInheritance(server);
	updateDfmSource(server);
	revealClass(server);
	openClass(server);
	openMethod(server);
	revealMethodInClass(server);
	queryReadonly(server);
	queryDatabase(server);
	getRecentExtensionErrors(server);
	getExtensionLogs(server);
	getRecentSqlQueries(server);
	startClientMcp(server);
	listClientMcpTools(server);
	callClientMcpTool(server);
	stopClientMcp(server);
	listNativeClientLogs(server);
	readNativeClientLog(server);
	listHttpMethods(server);
	startHttpTestServer(server);
	getHttpTestServerStatus(server);
	callHttpTestServer(server);
	stopHttpTestServer(server);
}
