import * as assert from 'assert';
import { registerTools } from '../mcp/tools/registration';

// Captured from the public catalog before splitting registration by domain.
const expectedNames = [
	"get_task_svn_commits",
	"refresh_task_svn_commits",
	"link_task_entity",
	"record_task_change",
	"record_task_verification",
	"record_task_decision",
	"propose_task_knowledge",
	"review_task_knowledge",
	"get_task_context",
	"find_tasks_for_entity",
	"search_task_knowledge",
	"save_task_progress",
	"save_completed_task",
	"search_completed_tasks",
	"get_completed_task",
	"mark_task_knowledge_transferred",
	"record_work_event",
	"get_recent_work_calls",
	"list_databases",
	"get_active_database",
	"switch_database",
	"lookup_object_by_id",
	"check_object_package_binding",
	"bind_objects_to_package",
	"search_database_objects",
	"search_classes",
	"get_class_details",
	"create_local_tool_class",
	"get_class_dictionary",
	"search_class_dictionary",
	"get_class_attributes",
	"get_attribute_details",
	"get_attribute_creation_options",
	"get_method_creation_options",
	"get_class_properties",
	"get_property_details",
	"search_methods",
	"resolve_method_reference",
	"get_method_source",
	"update_method_source",
	"create_class_method_checked",
	"compile_method",
	"get_method_compilation_history",
	"get_module_source",
	"update_module_source",
	"get_lifecycle_function_catalog",
	"execute_lifecycle_method",
	"update_database",
	"update_packages",
	"update_binaries",
	"start_client",
	"get_client_status",
	"open_client_entity",
	"get_svn_file_history",
	"get_package_sync_changes",
	"get_production_tasks",
	"get_production_task",
	"get_production_tasks_in_progress",
	"get_dfm_source",
	"get_dfm_inheritance",
	"update_dfm_source",
	"reveal_class",
	"open_class",
	"open_method",
	"reveal_method_in_class",
	"query_readonly",
	"query_database",
	"get_recent_extension_errors",
	"get_extension_logs",
	"get_recent_sql_queries",
	"start_client_mcp",
	"list_client_mcp_tools",
	"call_client_mcp_tool",
	"stop_client_mcp",
	"list_native_client_logs",
	"read_native_client_log",
	"list_http_methods",
	"start_http_test_server",
	"get_http_test_server_status",
	"call_http_test_server",
	"stop_http_test_server",
	"list_maps", "read_map", "save_map", "get_map_changes", "open_map"
];

suite('MCP registration compatibility', () => {
	test('preserves every public tool name and the exact registration order', () => {
		const names: string[] = [];
		registerTools({ registerTool: name => { names.push(name); } });
		assert.deepStrictEqual(names, expectedNames);
		assert.strictEqual(new Set(names).size, names.length);
	});
});
